[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
transferhook = "FWD3wDGsJc5ACV9fbDuV5VjprcSGfPvxzcb6WmbjjLm7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/leo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
